rootProject.name = "AdventOfCode"
include("Day01")
include("Day02")
include("Day02")
include("Day03")
include("Day04")
include("Day05")
include("Day06")
include("Day07")
include("Day08")
include("Day11")